# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continuous Integration with Guthub Actions

on:
  push:
    branches: 
      - "master" 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with: 
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Aplication Jar
      working-directory: ./productsdb
      run: mvn clean package -DskipTests 

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push to Docker Hub Container registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/productsdb:latest  ${{ secrets.DOCKER_USERNAME }}/productsdb:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/productsdb:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/productsdb:latest
